// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrFh1Z2uQN4jKT415iYa_7T6-W9f2EPg',
    appId: '1:1047859631371:web:2edd99410cf0b68472be0e',
    messagingSenderId: '1047859631371',
    projectId: 'emart-cb03a',
    authDomain: 'emart-cb03a.firebaseapp.com',
    storageBucket: 'emart-cb03a.appspot.com',
    measurementId: 'G-4JHDMNHDNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz05EIbvSQZqmstbQpjVtse_y-jObnYeE',
    appId: '1:1047859631371:android:a656cca42676a45672be0e',
    messagingSenderId: '1047859631371',
    projectId: 'emart-cb03a',
    storageBucket: 'emart-cb03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpXEEYAMuJjb_gqUesADiDkQPfh1GP04',
    appId: '1:1047859631371:ios:d4c1db4b040518da72be0e',
    messagingSenderId: '1047859631371',
    projectId: 'emart-cb03a',
    storageBucket: 'emart-cb03a.appspot.com',
    iosBundleId: 'org.spacademy.emartapp',
  );
}
